Upgrade jetty-server 7.6.8->7.6.13 for NIO fixes
Solve occasional failing jetty start caused by:

    java.lang.IllegalStateException: !Selecting

when using the max-queued option.

See also:
http://dev.eclipse.org/mhonarc/lists/jetty-users/msg02279.html
https://travis-ci.org/ring-clojure/ring/jobs/12571861